namespace AutomatedLab
{
    public partial class IPAddress
    {
        internal bool isAutoGenerated;

        public static IPAddress Null
        {
            get { return "0.0.0.0"; }
        }

        public bool IsAutoGenerated
        {
            get { return isAutoGenerated; }
        }
    }
}